
export const ROLE = {
    ADMIN:"ADMIN",//系统管理员
    REGISTRAR:"REGISTRAR",//教务员
    TEACHER:"TEACHER",//老师
    STUDENT:"STUDENT"//学生
}

export const PATH = {
    //admin
    Account_Management:{
        path:'/accountManagement',
        requiresAuth:[ROLE.ADMIN]
    },
    Login_Logs:{
        path:'/loginLogs',
        requiresAuth:[ROLE.ADMIN]
    },
    admin_Dashboard:{
        path:'/adminDashboard',
        requiresAuth:[ROLE.ADMIN]
    },
    //registrar
    AllThesis_Registrar:{
        path:'/allThesisRegistrar',
        requiresAuth:[ROLE.REGISTRAR]
    },
    Arrange_Defense:{
        path:'/arrangeDefense',
        requiresAuth:[ROLE.REGISTRAR]
    },
    Arrange_Printing:{
        path:'/arrangePrinting',
        requiresAuth:[ROLE.REGISTRAR]
    },
    Arrange_Review:{
        path:'/arrangeReview',
        requiresAuth:[ROLE.REGISTRAR]
    },
    Generate_Evaluation:{
        path:'/generateEvaluation',
        requiresAuth:[ROLE.REGISTRAR]
    },
    Plagiarism_Check:{
        path:'/plagiarismCheck',
        requiresAuth:[ROLE.REGISTRAR]
    },
    Advisor_Assignment:{
        path:'/advisorAssignment',
        requiresAuth:[ROLE.REGISTRAR]
    },
    Information_Management:{
        path:'/informationManagement',
        requiresAuth:[ROLE.REGISTRAR]
    },
    registrar_Dashboard:{
        path:'/registrarDashboard',
        requiresAuth:[ROLE.REGISTRAR]
    },
    //teacher
    Personal_Info:{
        path:'/personalInfo',
        requiresAuth:[ROLE.TEACHER]
    },
    Review_Management:{
        path:'/reviewManagement',
        requiresAuth:[ROLE.TEACHER]
    },
    AllThesis_Teacher:{
        path:'/allThesisTeacher',
        requiresAuth:[ROLE.TEACHER]
    },
    Approve_Defense:{
        path:'/approveDefense',
        requiresAuth:[ROLE.TEACHER]
    },
    Approve_Deferred:{
        path:'/approveDeferred',
        requiresAuth:[ROLE.TEACHER]
    },
    Approve_Draft:{
        path:'/approveDraft',
        requiresAuth:[ROLE.TEACHER]
    },
    Approve_Proposal:{
        path:'/approveProposal',
        requiresAuth:[ROLE.TEACHER]
    },
    Defense_Resolution:{
        path:'/defenseResolution',
        requiresAuth:[ROLE.TEACHER]
    },
    Review_Result:{
        path:'/reviewResult',
        requiresAuth:[ROLE.TEACHER]
    },
    Deferred_Approval:{
        path:'/deferredApproval',
        requiresAuth:[ROLE.TEACHER]
    },
    Formal_Submission:{
        path:'/formalSubmission',
        requiresAuth:[ROLE.TEACHER]
    },
    Modify_Resolution:{
        path:'/modifyResolution',
        requiresAuth:[ROLE.TEACHER]
    },
    Preliminary_Resolution:{
        path:'/preliminaryResolution',
        requiresAuth:[ROLE.TEACHER]
    },
    teacher_Dashboard:{
        path:'/teacherDashboard',
        requiresAuth:[ROLE.TEACHER]
    },
    //学生
    //TODO
    Student_Dashboard:{
        path:'/studentDashboard',
        requiresAuth:[ROLE.STUDENT]
    }
}